"""Changes made to tables and relationships

Revision ID: 1c13d629f8c3
Revises: 2fe23d0e6203
Create Date: 2024-08-07 11:13:41.873985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c13d629f8c3'
down_revision = '2fe23d0e6203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('result_desc', sa.String(length=255), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_payments_booking_id_bookings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('payment_method')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_payments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_booking_id_bookings', 'bookings', ['booking_id'], ['id'])
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('result_desc')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
