"""Dropped phone table

Revision ID: 1cd9f9113847
Revises: 1c13d629f8c3
Create Date: 2024-08-07 11:18:26.070370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd9f9113847'
down_revision = '1c13d629f8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_phones_booking_id_bookings'),
    sa.PrimaryKeyConstraint('id', name='pk_phones')
    )
    # ### end Alembic commands ###
