"""Phone table

Revision ID: 2fe23d0e6203
Revises: 8c1991dd53a6
Create Date: 2024-08-06 22:57:38.171447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe23d0e6203'
down_revision = '8c1991dd53a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_phones_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phones'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    # ### end Alembic commands ###
