"""changes

Revision ID: 6ed73eb5a4b2
Revises: 9b5e34e41a5e
Create Date: 2024-08-07 12:11:18.340939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed73eb5a4b2'
down_revision = '9b5e34e41a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('result_desc', sa.VARCHAR(length=255), nullable=True),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_payments_booking_id_bookings'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_payments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_payments')
    )
    # ### end Alembic commands ###
