"""added tickets table

Revision ID: 7b0457991af5
Revises: a8b21d6aa1d6
Create Date: 2024-08-06 11:03:11.570106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0457991af5'
down_revision = 'a8b21d6aa1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookings_ticket_id_ticket'), 'ticket', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_ticket_id_ticket'), type_='foreignkey')
        batch_op.drop_column('ticket_id')

    op.drop_table('ticket')
    # ### end Alembic commands ###
