"""Column added to payment table

Revision ID: 9b5e34e41a5e
Revises: 1cd9f9113847
Create Date: 2024-08-07 11:21:23.534217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5e34e41a5e'
down_revision = '1cd9f9113847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_booking_id_bookings'), 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_booking_id_bookings'), type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
